kind: pipeline
name: test

steps:

- name: Flake8
  image: python:3.7
  commands:
  - pip install flake8 > /dev/null
  - flake8

- name: Vagrant
  image: vmck/vagrant-vmck:0.1.0
  commands:
  - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
  - export SHUTDOWN=+30
  - cp examples/ecolex.ini ./
  - vagrant up
  - vagrant destroy
