---
- hosts: '*'
  tasks:

    - name: python pip
      become: true
      apt:
        name: python3-docker

    - name: cluster
      docker_container:
        name: cluster
        image: liquidinvestigations/cluster:norepo
        init: true
        privileged: true
        network_mode: 'host'
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /app/var:/app/var
        state: started
