---
- name: python pip
  become: true
  apt:
    name: python3-docker

- name: cluster
  docker_container:
    name: cluster
    image: liquidinvestigations/cluster:norepo
    init: true
    privileged: true
    network_mode: 'host'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/var:/app/var
    state: started

- name: wait for cluster
  shell:
    cmd: docker exec cluster ./cluster.py wait

- name: publish the secrets
  become: true
  shell:
    cmd: chmod 666 /app/var/vault-secrets.ini
